### ISSUE TITLE
The app nav bar should be the same width as the masonry grid

### ISSUE THREAD

**Issue by vojtechsimetka** [logos-innovation-lab/Kurate#142]
<img width="1673" alt="Screenshot 2023-02-05 at 15 17 37" src="https://user-images.githubusercontent.com/7974813/216806737-755aa3aa-d412-40c4-b257-b990ec65915d.png">
<img width="1652" alt="Screenshot 2023-02-05 at 15 17 03" src="https://user-images.githubusercontent.com/7974813/216806743-6b0afe24-cdf1-4c28-84a7-6b74cf3c90d4.png">
<img width="1651" alt="Screenshot 2023-02-05 at 15 16 51" src="https://user-images.githubusercontent.com/7974813/216806747-715723bc-3855-4a30-969a-87edc3989a3c.png">
<img width="1634" alt="Screenshot 2023-02-05 at 15 16 43" src="https://user-images.githubusercontent.com/7974813/216806751-36f42d1e-febc-46d8-9de0-fc6e2be08912.png">

**Comment by sugarpusher** [comment]
Yup I noticed this but since we're going to have to rework many components anyway, I figured I'd wait until we have the meeting with David to come up with a plan of action 😉

**Comment by sugarpusher** [comment]
Designer determined that app nav bar will always be fullwidth
