### ISSUE TITLE
[HELP] Persona pending

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/Kurate#178]
**Currently**
These posts are proposals currently being reviewed by the community. You can promote or demote a post by using a token. When a post gets enough positive reviews it will appear on the channel timeline and its creator will be rewarded anonymously.

**Matt's feedback**
The following are pending posts from anon contributors like you. Please help curate them by voting on whether they should be promoted to [Persona Name]'s timeline, or demoted into oblivion. Voting costs you 1 "GO" token, but you may use as many as you want on a single post (up to the limit of 30 per day) to show how much you believe a post should be promoted or demoted. A new post may be voted on for 4 hours; majority rules its fate. If you vote in line with the majority, you earn reputation proportional to the GO you spent voting on the post. The poster will receive or lose reputation based on the outcome of the vote.

![Image](https://user-images.githubusercontent.com/46993354/219017730-ae699af4-5ffb-4456-8198-76b538f57710.png)

**Comment by david-gauquelin** [comment]
@matthewcarano as we discussed yesterday we should have a shorter text (ideally even shorter than the one currently in the design) and a longer text in the FAQ

**Comment by matthewcarano** [comment]
Proposed edit:
The following are pending posts from anon contributors like you. Please vote on whether they should be promoted to [Persona Name]'s timeline, or demoted into oblivion. Voting costs you 1 GO, and you may use up to your daily limit. Voting in line with the majority earns you REP.

**Comment by david-gauquelin** [comment]
Should we use "anon" or "anonymous", I would prefer anonymous as it sounds less jargon
