### ISSUE TITLE
[HELP] Vote info

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/Kurate#179]
**Current**
This will use 1 GO
You will earn reputation if the majority of the community also promotes this content.

![Image](https://user-images.githubusercontent.com/46993354/219018627-4ad9d4c6-5326-493b-9254-6f818be02c00.png)

**Comment by david-gauquelin** [comment]
@matthewcarano you commented this in Sketch:

"We could explain here that reputation is also proportional to amount of "GO" spent on the vote. But perhaps it's enough that it was explained on the preceding screen."

AFAIK we have decided to not do proportional voting, so you can only vote with 1 GO

**Comment by matthewcarano** [comment]
If no proportional REP, here's my proposal. 

Proposed edit:
This will use 1 GO.
You will earn REP if the majority of the community also votes to promote this content.
