### ISSUE TITLE
[HELP] Vote error

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/Kurate#180]
Current

Sorry, you can't vote now
You need 1 GO to promote or demote content.

![Image](https://user-images.githubusercontent.com/46993354/219019303-9769d40d-3526-4aa0-9225-82402aaec605.png)

**Comment by matthewcarano** [comment]
Same as in Sketch, proposed in-app edit:

Sorry, you can't vote now.
You need  at least 1 GO to promote or demote content.
