### ISSUE TITLE
[HELP] Create persona — Placeholders

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/Kurate#181]
These are the text placeholders that should help people understand what to write when creating a persona
The "pitch" is the shorter text that is displayed on the persona cards on the homepage (before going to the persona page).
The "description" is shown on the header of the persona page

**Current**

Persona name
Enter a short memorable name…

Persona Pitch
Pitch the persona in one sentence, this should serve as a brief introduction…

Persona Description
Describe the persona in more details, provide additional context and help anyone understand the concept of this persona… 

![Image](https://user-images.githubusercontent.com/46993354/219020604-655cc674-babe-4492-b8c1-e853b686b32a.png)

**Comment by david-gauquelin** [comment]
@matthewcarano commented in Sketch

Perhaps: "Describe the persona in more detail to help everyone understand the concept of this persona..."

**Comment by matthewcarano** [comment]
Copy looks great to me with small changes in the Persona Description (the same as my feedback in Sketch noted above).

Proposed edit in Persona Description field:
Describe the persona in more detail to help everyone understand the concept of this persona……
