### ISSUE TITLE
[HELP] Persona - Saved draft

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/Kurate#183]
**Current**
This persona is saved as a draft (not public)
You will see it on your homepage. Before you can make it public you will need to create 5 “seed” posts. These posts should serve as inspiring examples for people willing to post with this persona.

![Image](https://user-images.githubusercontent.com/46993354/219022235-cc3d5f4b-b9d1-4794-973b-c4dfbb1164b7.png)

**Comment by matthewcarano** [comment]
Proposed in-app edit:
This Persona is saved as a draft (not public).

You will see it on your homepage. Before you can make it public you will need to create 5 “seed” posts. These posts should serve as inspiring examples for people who wish to post with this Persona.
