### ISSUE TITLE
[HELP] Seed posts info

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/Kurate#184]
![Image](https://user-images.githubusercontent.com/46993354/219022881-02b83f27-ab5b-4286-bbf1-7f819472b8df.png)

![Image](https://user-images.githubusercontent.com/46993354/219022667-d311c0f5-19a6-43cc-8e75-3853f8a0921d.png)

**Comment by matthewcarano** [comment]
Proposed in-app edit (eligible to publish screen):
You may now publish this Persona.

**Comment by david-gauquelin** [comment]
and "You need 5 seed posts to publish this persona", is that ok?

**Comment by matthewcarano** [comment]
> and "You need 5 seed posts to publish this persona", is that ok?

Sounds good. Maybe I put my comment on the wrong issue? It's referring to the eligible to publish screen, so apologies if that's confusing.
