### ISSUE TITLE
[HELP] Publish info — Error

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/Kurate#186]
![Image](https://user-images.githubusercontent.com/46993354/219023437-6b2ff149-e0fe-42b6-9ef5-ac3f8d05c0bd.png)

**Comment by matthewcarano** [comment]
Proposed in-app edit: (in general I think we should capitalize Persona)

You need 10 GO to publish a Persona

(in the currently available section)
Until new cycle begins.

**Comment by david-gauquelin** [comment]
"Until new cycle begins" — I love this

**Comment by matthewcarano** [comment]
> Shouldn't we say "You need _at least_ 10 GO to publish a Persona" — to be be consistent with your suggestion on voting error?

In the voting scenario, one can signal the weight of their belief by assigning more than the minimum votes to it.  (I can vote up to 30 on this one post)

In this case the cost is fixed at 10 GO to publish a Persona.

**Comment by david-gauquelin** [comment]
Ok, I understand now. So I removed "at least" everywhere because also for voting you can only vote once
