### ISSUE TITLE
[HELP] Persona published

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/Kurate#187]
![Image](https://user-images.githubusercontent.com/46993354/219023654-6dbe8c94-ba56-4489-b42d-92cd4a8c92ff.png)

**Comment by matthewcarano** [comment]
Proposed in-app edit: (mostly capitalization of Persona)

Published successfully

This Persona is now public

Anyone can now submit posts with this Persona. All posts will be subject to community review before being published. This Persona was added to your homepage.

**Comment by david-gauquelin** [comment]
I suggest that we say "[...] This Persona was added to _your favorites_."
