### ISSUE TITLE
[HELP] Submit reply

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/Kurate#188]
![Image](https://user-images.githubusercontent.com/46993354/219024113-d18f70ef-08fa-45f8-9341-65cbd3b208bf.png)

**Comment by david-gauquelin** [comment]
@matthewcarano commented in Sketch

Perhaps: "Your reply will be submitted to a community vote, and will be published if the majority votes to promote it. If promoted, you will earn 3 REP."

**Comment by david-gauquelin** [comment]
AFAIK yes, this works the same than for a post
source: https://hackmd.io/0W0ZkPexShqJ9Eu8CUO8pw

**Comment by david-gauquelin** [comment]
By the way, I would add: "If demoted, you will lose 3 REP."

**Comment by david-gauquelin** [comment]
I saw this from your other suggestion and I like this, I would keep this

"[...] If demoted, you will lose your staked REP."

**Comment by matthewcarano** [comment]
> 

Sounds good, let's do it.
