### ISSUE TITLE
[HELP] Submit post

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/Kurate#189]
![Image](https://user-images.githubusercontent.com/46993354/219024614-308e917d-ad2e-48d7-bc07-59c11d2c7d05.png)

**Comment by matthewcarano** [comment]
Proposed in-app edit:

Your post will be submitted to a community vote, and will be published if the majority votes to promote it. If promoted, you will earn 5 REP. If demoted you will lose your staked REP.

**Comment by david-gauquelin** [comment]
Detail: but I would add a coma after "if demoted".

"[...] If demoted, you will lose your staked REP."
