### ISSUE TITLE
[HELP] Post submitted to review

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/Kurate#191]
![Image](https://user-images.githubusercontent.com/46993354/219025382-ecfd544b-c30e-4e1e-9e1c-a0ee326fb0b9.png)

**Comment by matthewcarano** [comment]
Proposed in-app edit:
Your post has been added to "Persona name's" pending list for community review. If it gets promoted it will be automatically published to "Persona name's" timeline.

**Comment by david-gauquelin** [comment]
I would prefer to use the word "page" instead of "timeline". I'm trying to get away from the timeline looks with the Persona page.

**Comment by david-gauquelin** [comment]
Shouldn't we add something about time as well? Like: [...]will be automatically published to Persona name's timeline when the new cycle begins

**Comment by matthewcarano** [comment]
> 

Sure how's this:

Your post has been added to "Persona name's" pending list for community review. If it gets promoted it will be automatically published to "Persona name's" page when the new epoch begins.

**Comment by david-gauquelin** [comment]
Thanks Matt. Should we use "epoch" or "cycle" ?— on another card you suggested "until new cycle begins".

**Comment by matthewcarano** [comment]
Good question. I might have just been following your lead with "cycle" on the other card. I think epoch makes the most sense throughout? It has one definition that I know of and people in the industry are used to it — would be my arguments for.

**Comment by david-gauquelin** [comment]
This came up in a discussion with Michelle & Kiki yesterday. Michelle and I have a preference for "cycle" as we feel that this is a simpler word — epoch has an "historical feel" to it. Would you be ok with cycle?

**Comment by michelleplur** [comment]
Maybe we can also think about localization, and crowd/community source the translations?
