### ISSUE TITLE
[HELP] Closed chat

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/Kurate#193]
![Image](https://user-images.githubusercontent.com/46993354/219026535-e86a9dac-04d6-47f9-a761-687e5f6403ef.png)

**Comment by matthewcarano** [comment]
Not sure we need the second sentence. I imagine knowing the history will be preserved is more relevant when a chat gets closed. Consider keeping just the first sentence.

**Comment by david-gauquelin** [comment]
You mean before I click on close chat I assume. Makes sense.
