### ISSUE TITLE
[HELP] GO amount headers

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/Kurate#196]
![Image](https://user-images.githubusercontent.com/46993354/219027409-d139cdea-ba65-407b-8f07-97c15799d6ea.png)
![Image](https://user-images.githubusercontent.com/46993354/219027408-e34c83d6-c6ed-4a14-b864-6acc5095e04b.png)

**Comment by matthewcarano** [comment]
Good to me
