### ISSUE TITLE
[HELP] Account

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/Kurate#198]
![Image](https://user-images.githubusercontent.com/46993354/219027851-3c97cb49-a8c2-413a-b208-dbd4a281850c.png)

**Comment by david-gauquelin** [comment]
@matthewcarano also here we should decide if we use "epoch" or "cycle" or anything else :)

**Comment by matthewcarano** [comment]
I think "epoch". I commented here as well: https://github.com/logos-innovation-lab/Kurate/issues/191#issuecomment-1441311913
