### ISSUE TITLE
Epic 2: Connect wallet

### ISSUE THREAD

**Issue by kikipluche** [logos-innovation-lab/Kurate#22]
connect with key-card, this epic is about connecting to a key-card or browser-wallet. There is no design needed, but only hooking up the action of connecting a wallet.

**Comment by kikipluche** [comment]
also need to check on the visuals for keycard connection:
are these 2 the actions that are needed to create an account with key-card?

![Image](https://user-images.githubusercontent.com/9036081/204521108-a9b94c72-2c96-4d61-8874-3d51e3115d5e.png)


![Image](https://user-images.githubusercontent.com/9036081/204521003-a3ef5b79-2238-4f06-ba26-3065fca270a8.png)

**Comment by vojtechsimetka** [comment]
@kikipluche how can we best review this and ideally close? :)
