### ISSUE TITLE
[Design] Add REP feature to Persona

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/Kurate#226]
The idea is to explore how could we have Personas that require a minimum amount of REP to submit posts through them.

- There should be a way to define the REP threshold while creating a persona #231 
- The minimum needed REP should be visible on the Persona card and Persona page
- We should add a sorting option on list of Personas (in order to sort by REP) #232 
- We should have error states to display when someone tries to submit a post but doesn't have enough REP

How to deal with staked REP?
- I think that staked REP should still be included in my REP counting. For example if a Persona has a REP threshold of 20 and, in the current cycle I have 25 REP total with 10 staked REP I should be allowed to submit a post (as long as I still have 5 REP available to stake). Of course staked REP can't be used to stake twice in the same cycle

**Comment by david-gauquelin** [comment]
I would suggest that I can't create a Persona with a higher REP threshold than my current REP total.

**Comment by vojtechsimetka** [comment]
All build, closing
