### ISSUE TITLE
[HELP] Define REP — Create Persona

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/Kurate#230]
Reputation level

—

Choose how much REP is needed to submit a post through this Persona. Higher values means a more reputable Persona, but make it accessible to less people.

—

You currently have 61 REP. You can’t choose a reputation level above your current REP total.

![Image](https://user-images.githubusercontent.com/46993354/222379128-0b1a6d36-6b7e-4a6d-85ee-10015401311b.png)

**Comment by matthewcarano** [comment]
Could perhaps simplify the first section a little to:

Choose how much REP is needed to submit a post through this Persona. Higher values means a more reputable Persona, but accessible to less people.


Second section copy looks good.
