### ISSUE TITLE
Define REP thresholds for Persona

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/Kurate#231]
I'm proposing to use a dropdown to define the REP threshold when creating a Persona. I think that this makes it simpler to use pre-defined steps. I was thinking about 5 steps. Please help define the values and naming (if needed?)

Also I thought that it would be good to not let me create a Persona with a higher threshold than my current REP. This is why some options are greyed out in one of the screenshot below.

![Image](https://user-images.githubusercontent.com/46993354/222385020-8cad7e8e-5ce2-4c1f-8cf6-c3786b18d03a.png)
![Image](https://user-images.githubusercontent.com/46993354/222384670-d5dbc343-b6ce-44ac-9fba-312386d5e07e.png)
![Image](https://user-images.githubusercontent.com/46993354/222384671-65d4f372-9ed6-4433-a7f5-448441d16f62.png)

**Comment by matthewcarano** [comment]
I like the dropdown and the creator requirement of REP threshold. I considered the threshold names as: minimum, low, medium, high, maximum, but I like yours better. The numerical values seem good to me, butI honestly don't know until we mess with it what's best.

**Comment by david-gauquelin** [comment]
We agreed to start with these values

**Comment by vojtechsimetka** [comment]
All build
