### ISSUE TITLE
[HELP] Not enough REP to submit post

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/Kurate#233]
This should be shown when a user tries to submit a post through a Persona that has a higher REP threshold then his current total (in this cycle)

![Image](https://user-images.githubusercontent.com/46993354/222419003-19318f65-5968-4774-9b3e-8de970547d2c.png)

**Comment by matthewcarano** [comment]
All looks good, except I propose the header says: "Not enough REP"
