### ISSUE TITLE
REP threshold — open questions

### ISSUE THREAD

**Issue by david-gauquelin** [logos-innovation-lab/Kurate#234]
- [x] #231 
- [x] While creating a Persona, can I set a higher REP threshold than my current total REP?
- [x] Interesting case: I created a Persona in a previous cycle and saved it as a draft. Now (in a next cycle), I lost some REP and I'm under the REP threshold I set for this Persona. Can I add seed posts? Can I publish it?
- [x] When I want to submit a post to a Persona, do we count my total REP (including staked REP) or my available REP (excluding staked REP)? 
- [x] If I don't have 5 REP I shouldn't be able to start creating a Persona? Otherwise we might have an issue with the threshold dropdown if I can't select anything

**Comment by david-gauquelin** [comment]
After talking to @vojtechsimetka and @sugarpusher a simpler idea could be to not check REP for writing seed posts but rather at the moment of publishing

**Comment by david-gauquelin** [comment]
I would display an alert/error if I click on create Persona and I don't have 5 REP

**Comment by david-gauquelin** [comment]
So I think we've answered all the questions here.

> While creating a Persona, can I set a higher REP threshold than my current total REP?
NO. We shouldn't allow me to select a higher REP than my current **total REP** (including staked REP).

> Interesting case: I created a Persona in a previous cycle and saved it as a draft. Now (in a next cycle), I lost some REP and I'm under the REP threshold I set for this Persona. Can I add seed posts? Can I publish it?
We can add seed posts regardless of the amount REP we currently have. But we check the REP total when I click on Publish Persona and if I have less than the Persona threshold I can't publish, we display an error. The Persona stays in draft until I can publish it (I can also modify the REP threshold).

> When I want to submit a post to a Persona, do we count my total REP (including staked REP) or my available REP (excluding staked REP)?
We count the **total REP** (including staked REP). The reasoning is that we still consider that I owned staked REP in this cycle.

> If I don't have 5 REP I shouldn't be able to start creating a Persona? Otherwise we might have an issue with the threshold dropdown if I can't select anything
NO. We should have at least 5 REP to start creating a persona. We check this when someone clicks on "create persona". If not we display an error.

**Comment by vojtechsimetka** [comment]
All build, closing the issue
