### ISSUE TITLE
Review image sizes

### ISSUE THREAD

**Issue by vojtechsimetka** [logos-innovation-lab/Kurate#286]
Currently we use maximum of:

`500 x 500` for pictures included in post
`1440 x 810` for persona cover picture
`500 x 500` for persona profile pictures

For technical reasons these were kept as small as possible, but now that we use IPFS even for pictures of draft personas, we can make them larger.

WDYT, what sizes should these be @david-gauquelin ?

**Comment by david-gauquelin** [comment]
**For pictures included in post:**
The maximum column width is `450pt`, so @2x resolution this would give us a maximum width of `900px` when there's only 1 picture added. If this is a vertical image I would set a maximum height of `450pt`, so `900px` @2x resolution. Note that when there's only 1 picture, we should keep the original ratio. When we have 2 images, we crop them into a square format of ´222pt´, so ´444x444px´ @2x resolution. Lastly when we have 3+ images we use the 3 squares layout, in this case the square size is ´146pt´, so ´292px´@2x resolution.

**Comment by david-gauquelin** [comment]
**For Persona cover picture**
`1440x810px` is correct. That's 16:9 ratio and large enough to look good on most screen sizes, it should be a good compromise.

**Comment by david-gauquelin** [comment]
**For Persona  profile picture**
The maximum size we need is indeed `250x250pt` so at 2x resolution this is `500x500px`.

@vojtechsimetka similar comment than for post pictures, if we want to create optinized sized copies let me know. For example when we use the Persona profile picture on a list, the biggest size is `99x99pt` so `198px`(instead of 500).

**Comment by vojtechsimetka** [comment]
Thanks!

No we don't want to create multiple optimized copies at least for now. Max size `900x900px` is not that horrible to download it all.

As for the multiple images in a post. I think we should still keep `900x900px` for each one of them because we can browse them in full screen, right?

**Comment by david-gauquelin** [comment]
Right

**Comment by vojtechsimetka** [comment]
So the max sizes for now are:

`500 x 500px` for pictures included in post
`1440 x 810px` for persona cover picture
`900 x 900px` for persona profile pictures

We will review as we play with the app but I am closing this issue as it is implemented in PR #291
