### ISSUE TITLE
Firefox On Mac: Votes to promote not tallying but GO is reduced

### ISSUE THREAD

**Issue by matthewcarano** [logos-innovation-lab/Kurate#316]
https://user-images.githubusercontent.com/30149603/229362547-f5ddf060-a075-4835-96cc-5a28b31df6b6.mov

On a Pending post, tried to "Promote". Everything seemed to work fine, the signing screen in Metamask came up. the GO token was reduced. But the Promote did not occur. I was able to vote again, again the GO token was reduced, but Promote confirmation button did not show. I then tried to Demote, which worked correctly. (video attached)

**Comment by vojtechsimetka** [comment]
@matthewcarano can you please check if this is still an issue?

**Comment by matthewcarano** [comment]
@vojtechsimetka works now!
