### ISSUE TITLE
Styling: in some browsers icons are not in the center of button

### ISSUE THREAD

**Issue by vojtechsimetka** [logos-innovation-lab/Kurate#320]
![Screenshot 2023-04-01 at 22 21 10](https://user-images.githubusercontent.com/7974813/229365605-00b33b64-7648-4431-9b6a-59994d30c9d7.png)

**Comment by sugarpusher** [comment]
@vojtechsimetka 
Can you specify which browsers?

**Comment by vojtechsimetka** [comment]
This was Brave I believe and also status browser :/

**Comment by sugarpusher** [comment]
Resolved with #342
