### ISSUE TITLE
Style: fix spacing on select reputation page

### ISSUE THREAD

**Issue by vojtechsimetka** [logos-innovation-lab/Kurate#324]
![Screenshot 2023-04-01 at 22 28 38](https://user-images.githubusercontent.com/7974813/229365757-c9c09670-c899-4b45-8bcd-c07ed0510ef7.png)
![Screenshot 2023-04-01 at 22 28 34](https://user-images.githubusercontent.com/7974813/229365758-7d0cb498-9d50-40a1-afa9-d34fab612d48.png)

**Comment by sugarpusher** [comment]
Resolved in #340
