### ISSUE TITLE
Style: on mobile some buttons should probably be just icons

### ISSUE THREAD

**Issue by vojtechsimetka** [logos-innovation-lab/Kurate#326]
![Screenshot 2023-04-01 at 22 32 33](https://user-images.githubusercontent.com/7974813/229365997-5099d6f2-3d98-45cf-8ec3-7cccb69edc49.png)

**Comment by sugarpusher** [comment]
Do we need David's ok to execute this?

**Comment by vojtechsimetka** [comment]
IMHO no
