### ISSUE TITLE
Unselected "Chats" and "Personas" buttons font should be light

### ISSUE THREAD

**Issue by matthewcarano** [logos-innovation-lab/Kurate#333]
As seen on Brave and Chrome

<img width="1429" alt="Screenshot 2023-04-02 at 12 38 09 PM" src="https://user-images.githubusercontent.com/30149603/229366584-b3c9b821-9169-4733-8934-82867b3bbec4.png">

<img width="1180" alt="Screenshot 2023-04-02 at 12 40 30 PM" src="https://user-images.githubusercontent.com/30149603/229366622-3e3cfde2-d147-425f-a113-10605fd1e34e.png">

**Comment by sugarpusher** [comment]
Resolved with #345
