### ISSUE TITLE
App jiggles in certain situations

### ISSUE THREAD

**Issue by matthewcarano** [logos-innovation-lab/Kurate#346]
Jiggle occurs on second monitor in Brave when the browser is more "square". Does not happen on mainMac screen,
https://user-images.githubusercontent.com/30149603/229374087-7dd6492f-3000-4df7-9ee3-72176099838a.mov

**Comment by vojtechsimetka** [comment]
Yeah this is because when you start scrolling, the top bar gets smaller and the page no longer needs to be scrolled so `scrollY`. The solution here is to not make the top bar smaller but animat the button position as we scroll. Probably not a priority but it is quite annoying :(

**Comment by vojtechsimetka** [comment]
I would love to open a discussion about this topic @sugarpusher . Do you think we can have the `<header>` to always have second element that stays underneath, has same height as the header and does not change to `position: static`? Do you think that is a good solution? Hence the screen would not shrink. We can sort this with JS, I have an idea.
