### ISSUE TITLE
Comment out/remove all darkmode media queries

### ISSUE THREAD

**Issue by vojtechsimetka** [logos-innovation-lab/Kurate#347]
I think we should comment out or even better remove all such media queries. I don't think we will implement dark mode, right? And it seems that if the user prefers darkmode it looks horrible :(

_Originally posted by @vojtechsimetka in https://github.com/logos-innovation-lab/Kurate/pull/345#pullrequestreview-1368131116_

**Comment by sugarpusher** [comment]
Currently working on this, there are still some leftover instances. I'm commenting out because I remember us discussing at a team meeting that we might decide to implement later.
