### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getChatByUser')  

### ISSUE THREAD

**Issue by vojtechsimetka** [logos-innovation-lab/Kurate#412]
This happens when the app is initiated and the problem is that `this.zkitter` is undefined in the adapter (gets populated after few seconds). The solution is to correctly check for `undefined` values and in this specific instance delay the execution until `this.zkitter` is defined.

https://github.com/logos-innovation-lab/Kurate/blob/main/packages/ui/src/lib/adapters/zkitter/index.ts#L157-L159

**Comment by 0xtsukino** [comment]
this seems to be caused by calling `syncChat` before `start` is called correct?

i think the correct fix here is to implement a `waitForStart` method in the adapter that resolves once `start` is finished, and call `this.waitForStart()` in methods like `syncChat`
